# Generated by Django 4.2.6 on 2023-11-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_coursemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='booksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books_name', models.CharField(max_length=100)),
                ('written_by', models.CharField(max_length=100)),
                ('book_pages', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
