# Generated by Django 4.2.6 on 2023-11-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booksmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='course',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='course_name',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='main.coursemodel'),
            preserve_default=False,
        ),
    ]
