# Generated by Django 4.2.6 on 2023-11-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_studentmodel_course_studentmodel_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='course_name',
        ),
    ]
