# Generated by Django 4.2.6 on 2023-11-02 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_studentmodel_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='course_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.coursemodel'),
            preserve_default=False,
        ),
    ]
