# Generated by Django 4.2.6 on 2023-11-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_studentmodel_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_faculaty_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
