# Generated by Django 4.2.6 on 2023-11-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentmodel_course_faculaty_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='course_faculaty_name',
        ),
    ]
