# Generated by Django 4.2.6 on 2023-11-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_studentmodel_course_faculaty_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='status',
            field=models.CharField(choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate')], default='Pending', max_length=50),
        ),
    ]
