# Generated by Django 4.2.6 on 2023-11-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_teachersmodel_delete_studentsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teachersModel',
            new_name='adminModel',
        ),
    ]
