# Generated by Django 4.2.6 on 2023-11-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_teachersmodel_adminmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmodel',
            name='course',
        ),
    ]
